name: CI/CD Pipeline for Common Services

on:
  push:
    branches:
      - develop
    paths:
      - 'common-services/**'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd common-services
          npm install

      - name: Run tests
        run: |
          cd common-services
          npm test

      - name: Build and Deploy
        run: |
          cd common-services
          npm run build
