name: CI/CD Pipeline for Common Services

on:
  push:
    branches:
      - develop
    paths:
      - 'common-services/**'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Install AdoptOpenJDK
          java-version: '11'     # Adjust based on your Java version

      - name: Build with Maven
        run: |
          cd common-services
          mvn install

      - name: Run tests
        run: |
          cd common-services
          mvn test