name: CI/CD Pipeline for Common Services (Java)

on:
  push:
    branches:
      - develop
    paths:
      - 'common-services/**'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Or 'temurin'
          java-version: '17'     # Set Java version to 17

      - name: Build with Maven
        working-directory: common-services  # Specify the correct directory
        run: mvn install

      - name: Run tests
        working-directory: common-services  # Specify the correct directory
        run: mvn test
